---
- name: report domains for certificate ({{ name }})
  debug:
    msg: "{{ name }} >> {{ domains |join(' ') }}"

- name: remove old letsencrypt certificate (ok to fail) ({{ name }})
  command:
    argv:
      - certbot
      - delete
      - --cert-name
      - "{{ name }}"
      - --non-interactive
    removes: "{{ cert_subdir }}"
  ignore_errors: true
  when: remove_existing |bool

- name: create or update letsencrypt certificate ({{ name }})
  command:
    argv:
      - certbot
      - certonly
      - --dns-cloudflare
      - --cert-name
      - "{{ name }}"
      - --domains
      - "{{ domains |join(',') }}"
      - --non-interactive
      # - --dry-run
    creates: "{{ update_existing |ternary(omit, cert_subdir) }}"
  register: certonly_result
  changed_when: "not (certonly_result.stdout |default(''))
                     .startswith('skipped, since')
                 and (certonly_result.stderr |default(''))
                     .find('Keeping the existing certificate') < 0"
  retries: 3
  until: certonly_result is successful
  tags: cert_cf_renew_cert

- name: fix permissions of the private key ({{ name }})
  file:
    path: "{{ cert_subdir }}/privkey.pem"
    group: "{{ certbot_group }}"
    # not setting state, but 'link' is assumed
    mode: 'o='  # disable others (as required by e.g. postgresql server)
  tags: cert_cf_renew_cert
...
